### ISSUE TITLE
password does not work

### ISSUE THREAD

**Issue by cjieming** [sayan91/health-analytics-ucsf#1]
Hi I installed vagrant and tried ssh but the password does not seem to work. Help?

**Comment by maryamv** [comment]
Same here.  The password dose not work.

**Comment by shaayohn** [comment]
Hi,

Could you please tell me what OS you’re running on?

Thanks,
Sayan

**Comment by shaayohn** [comment]
The password for your box should be in the file at the following location:

```~/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20170410.0.0/virtualbox/Vagrantfile```

**Comment by neuralinfo** [comment]
Are copying/pasting the password from the markdown or manually entering the
password?

**Comment by maryamv** [comment]
I'm using manOS Sierra (vs. 10.12.3)

**Comment by maryamv** [comment]
I tried copy-pasting and manually entering the password multiple times

**Comment by shaayohn** [comment]
maryamv, the password for your box should definitely be at the location I put up earlier. Open that file with your favorite text editor and look for the password.

EDIT: I have updated the location I put up earlier. The new password has been updated in a new version of the box.

**Comment by cjieming** [comment]
Got it. It works now - the password on the README.md in the folder before only had the old password, so it didnt work. But the one in the folder `~/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20170410.0.0/virtualbox/Vagrantfile` worked! Thanks @sayan91 !

**Comment by maryamv** [comment]
Hi Sayan,

So I think I made it work with the password you provided but I don't have
any directory by the name .vargrant.d to search for the password (I only
have .vargrant

Thanks,
Maryam
